package com.lbb.customer.statement.http.termdeposit;

import lombok.Data;

import java.math.BigDecimal;

@Data
public class TdaRec {
    private String acctNo;
    private BigDecimal principalAmt;
    private Integer depTermPeriod;
    private String depTermType;
    private Integer depTermDays;
    private String maturityDate;
    private String autoRenewRollover;
    private String billOfExchange;
    private Integer renewNo;
    private Integer rolloverNo;
    private String lastMvmtDate;
    private String lastMvmtStatus;
    private Integer timesRenewed;
    private Integer timesRolledover;
    private String prevInternalKey;
    private String prevAccountNo;
    private String tdBonfType;
    private BigDecimal principalBonusRate;
    private String certPrinted;
    private String matNotice;
    private String underLien;
    private String partialRenewRoll;
    private BigDecimal principalAmtActual;
    private String addtlPrincipal;
    private BigDecimal totalAddtlPrincipal;
    private Integer tdGracePeriod;
    private BigDecimal prinAvailedAmt;
    private BigDecimal addtlDepAvailedAmt;
    private BigDecimal prinAvailedAmtAwr;
    private String partialWdrawInd;
    private String tdGracePeriodType;
    private String tdGracePeriodValidDate;
    private Integer wdrawRealPeriod;
    private String wdrawRealPeriodType;
    private String wdrawValidDate;
    private Integer tdRevChangePrd;
    private String tdRevChangePrdType;
    private String tdRevChangeValidDate;
    private BigDecimal penaltyInRevPeriod;
    private String prinWithoutPenalty;
    private BigDecimal prinWithoutPenaltyAmt;
    private String prevAcctNo;
    private Integer daysWithNoRate;
    private BigDecimal addtlDepAvailableAmt;
    private String claimOnIntBonus;
    private String daysWithNoRateType;
    private BigDecimal totalAddtlIntPrincipal;
    private BigDecimal addtlDepIntAvailedAmt;
    private BigDecimal addtlDepIntAvailableAmt;
    private BigDecimal prinAvailableAmt;
    private BigDecimal intBonus;
    private String tdRelationInd;
    private String channel;
    private String channelSource;
    private String channelDetailInfo;
    private String channelRefNo;
    private Object domesticClearingUaeFtsCb103Rec;
    private Integer version;
    private Integer bizVersion;
    private String createdBy;
    private String createdDt;
    private String journalDt;
    private Long journalNo;
    private String modifiedBy;
    private String modifiedDt;
    private Object virtualAttributeList;
    private Object dataExtensionList;
    private Object header;
    private Object securityHint;
    private Object digitalSignature;
    private String hasNextYn;
    private Object messageInfoList;
    private Boolean hasError;
    private String publicKey;
    private String lastSuccessfulValidation;
    private String changeSummary;
}
