package com.lbb.customer.statement.model;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.Data;

import java.math.BigDecimal;
import java.util.List;

@Data
public class TransactionData {
    private Long seqNo;
    private String tranDate;
    private String acctNo;
    private String certificateNo;
    private String effectDate;
    private String tranType;
    private String crDrMaintInd;
    private BigDecimal tranCcyAmt;
    private String ccy;
    private BigDecimal tranAmt;
    private String reference;
    private String tranDesc;
    private String sourceRefType;
    private String sourceRefNo;
    private String crStatCode;
    private String drStatCode;
    private String sourceType;
    private String sourceModule;
    private Integer floatDays;
    private String referenceBank;
    private String referenceBranch;
    private String postDate;
    private String branch;
    private String purposeCode;
    private String entryDate;
    private String profitCentre;
    private String specCode;
    private String tranRefNo;
    private String taxable;
    private String taxDueToInt;
    private String servCharge;
    private String reversalInd;
    private String tfrAcctNo;
    private Long tfrSeqNo;
    private String stmtDetail1;
    private String rateType;
    private String channel;
    private String channelSource;
    private String channelRefNo;
    private String channelDetailInfo;
    private String terminalId;
    private String officerId;
    private BigDecimal previousBalAmt;
    private BigDecimal actualBalAmt;
    private String timeStamp;
    private Long journalSeqNo;
    private Long mvmtSeqNo;
    private String msgClient;
    private String othBankCode;
    private String othAcctNo;
    private String othAcctDesc;
    private String othReference;
    private String othSpecCode;
    private String othValueDate;
    private String referenceType;
    private String reversalTranType;
    private String reversalDate;
    private String pbkUpdFlag;
    private String stmtDate;
    private String traceId;
    private String overrideOfficer;
    private String brSeqNo;
    private String cdCashFlowFlag;
    private String valueDate;
    private String btOfficerId;
    private String btOverrideId;
    private String receiptNo;
    private String primarySeqNo;
    private String specificSymbol;
    private String othAcctDesc2;
    private String clientCrossRef;
    private String ttrn;
    private BigDecimal othAmt;
    private BigDecimal wdlPenaltyAmt;
    private BigDecimal intAmtWdrawn;
    private String wdlNoticeInd;
    private String clientName;
    private String idType;
    private String clientId;
    private String address;
    private String resident;
    private String clientType;
    private String categoryType;
    private String country;
    private String domesticForeign;
    private String placeOfIssuance;
    private String variableSymbol;
    private String penaltyApplyWay;
    private String availedWdlAmt;
    private String printed;
    private String consolidateItem;
    private Long consSeqNo;
    private Integer sortPriority;
    private String permissionNo;
    private String dpTranDate;
    private Long dpSeqNo;
    private String ccyConv;
    private String origTranDate;
    private Long reversalSeqNo;
    private Long wdlSeqNo;
    private Long grpTranSeqNo;
    private String instCode;
    private String billReference;
    private String sdbInternalKey;
    private String sdbTranInd;
    private String voucherNo;
    private String acctCcy;
    private String startDt;
    private String endDt;
    private Long revTranSeqNo;
    private Long revContraTranSeqNo;
    private String tranHistFcyRec;
    private String cPartyRec;
    private String tranHistIbftRec;
    private Integer version;
    private Integer bizVersion;
    private String createdBy;
    private String createdDt;
    private String journalDt;
    private Long journalNo;
    private String modifiedBy;
    private String modifiedDt;
    private List<Object> virtualAttributeList;
    private List<Object> dataExtensionList;
    private Object header;
    private String securityHint;
    private String digitalSignature;
    private String hasNextYn;
    private List<Object> messageInfoList;
    private String hasError;
    private String publicKey;
    private String lastSuccessfulValidation;
    private String changeSummary;

    @Override
    public String toString() {
        try {
            return new ObjectMapper().writeValueAsString(this);
        } catch (JsonProcessingException e) {
            return "Error serializing to JSON: " + e.getMessage();
        }
    }
}
